### ISSUE TITLE
GUI - obracanie prostokątów

### ISSUE THREAD

**Issue by mmaka** [mmaka/ProgZesp#14]
po dodaniu prostokąta "z ręki" lub z "ostatnio rozmieszczonych" powinna być możliwość łatwej zamiany wysokości i szerokości.  
np. 
1) gdyby użytkownik się pomylił to musiałby usuwać i wprowadzać nowe dane a można to załatwić jednym kliknięciem
2) wybieramy prostokąt spośród wcześniej rozmieszczanych, ale tym razem chcemy aby był obrócony o 90 stopni

**Comment by Dawdios** [comment]
Zrobiłem tak: użytkownik wybiera z listy figurę i klika edytuj. Otwiera się okienko z możliwością wpisania nowych wartości szerokości i długości.  Mam też dodać przycisk "Obróć" który po prostu zamieni szerokość z długością ?

**Comment by mmaka** [comment]
Tak, przycisk będzie użyteczny bo to ma być prosta operacja. Jeśli obrót miałby wymagać więcej kliknięć niż usunięcie i dodanie nowego prostokąta, to byłoby bez sensu.

Chodzi również o to że podczas dodawania prostokąta potrzebujemy aby użytkownik zaznaczył checkbox pozwalający na obracanie prostokątów. Nie zawsze obroty są dopuszczalne - jeżeli chcesz wycinać kilka prostokątów deski na jakieś drzwi czy szafki to dobrze słoje muszą być ustawione w ten sam sposób (czyli obracanie byłoby zabronione). W klasie Prostokąt powinno być takie pole. Próbując rozwiązać problem #15 będzie trzeba korzystać z tego pola.
