### ISSUE TITLE
Wydajność

### ISSUE THREAD

**Issue by inskript** [mmaka/ProgZesp#16]
Trzeba rożłożyć metody Michała na wątki bo MULI

**Comment by mmaka** [comment]
Może zaczniemy od propozycji @dawidgrusz1995 dotyczącej for-a, którego każdy przebieg jest osobnym wątkiem.

**Comment by Dawdios** [comment]
Ja dodawałem po 1000 figur i jakoś specjalnie nie muliło. Zamieniłem jednak pierwszego fora z funkcji "generuj_rozmieszczenia" na Parallel. Wydawało mi się że lepszym wyborem będzie zastosowanie Parallel dla 2 fora ponieważ właśnie ta pętla wykonuje się wiele razy - okazało się jednak że znajdujące się wewnątrz działania miały na siebie wpływ przez co program wypluwał błędne rozmieszczenia

**Comment by mmaka** [comment]
Co do wydajności to Wasza wersja zmniejsza liczbę indeksowań (czyli rozpatrywanych rozmieszczeń) w pętli do-while. To nie było dobre rozwiązanie i zmieniłem na obracanie stałą liczbą indeksowań-rozmieszczeń. Więc liczba przebiegów tego pierwszego for-a jest duża. I chcemy żeby była jak największa (ale jednak tak by program nie "mulił"). Ten drugi for przebiega dużo razy, ale tylko wtedy gdy masz dużo figur - i rzeczywiście każdy przebieg miał wpływ na kolejny, bo tutaj jest zajmowana pozycja na matrycy i uzupełniania tablica zajętości (przy równoległości dwa różne prostokąty zaczynają szukać sobie miejsca na matrycy z tą identycznym stanem tablicy zajętości). 

Jeszcze wyjaśnienie dlaczego ten pierwszy for jest ważniejszy (tzn. ważniejsze jest żeby był szybki): jak masz 10 prostokątów to żeby umieścić je "sensownie" na matrycy potrzebujemy rozpatrzeć jak największą liczbę różnych indeksowań - czyli różnych kolejności umieszczania prostokątów. Najlepiej byłoby badać wszystkie kombinacje, ale tego robić nie możemy bo dla 10 figur to jest 10! kombinacji... a dla testowanego przez Ciebie 1000 figur było by 1000! Wszechświat by przestał istnieć zanim by się skończyło działanie programu ;) 

Dzięki za te równoległość!!
