### ISSUE TITLE
Co rysować?

### ISSUE THREAD

**Issue by inskript** [mmaka/ProgZesp#17]
Czy wystarczy rysowanie najlepszego rozłożenia?

**Comment by mmaka** [comment]
Hmmmm... Zdaje się, że ta wersja którą pobrałeś ode mnie jako wynik dawała jedno rozmieszczenie. Teraz jest trochę inaczej. Dostajemy całą listę rozmieszczeń. Każde z nich ma swoją miarę użyteczności i można rysować najlepsze rozłożenie - czyli dla Ciebie nic by się nie zmieniło, tylko ja musiałbym znaleźć najlepsze rozmieszczenie na liście. 

Ale czasami na tej liście jest kilka najlepszych (z tą samą miarą) rozmieszczeń, więc można by je np. użytkownikowi pokazać żeby wybrał. Albo w jakiejś zakładce z ustawieniami można dać użytkownikowi możliwość decyzji czy chce zobaczyć kilka najlepszych rozmieszczeń.
