### ISSUE TITLE
Zabezpieczenie przed prostokątami większymi od rozmiarów matrycy

### ISSUE THREAD

**Issue by mmaka** [mmaka/ProgZesp#18]
w tym momencie takie prostokąt spowoduje nieskończoną pętlę (dodawania nowej matrycy do listy i próbę umieszczenia prostokąta)

**Comment by Dawdios** [comment]
Nie wiem czy o to dokładnie chodziło, ale zrobiłem to tak: sprawdzam listę wszystkich stworzonych matryc i porównuję ich wielkości do Prostokąta. Jeśli jest większy to pojawia się MessageBox z informacją że prostokąt jest za duży w porównaniu do dostępnych matryc .

**Comment by mmaka** [comment]
hmmm, tylko pytanie w którym etapie działania programu robisz to sprawdzenie? Program pobiera prostokąt z listy i próbuje go umieścić na matrycy, jeśli nie daje rady to tworzy nową matrycę i znowu próbuje go umieścić. Czyli mamy nieskończoną pętlę.

Z jednej strony musimy się zabezpieczyć przed rozmiarami prostokątów większymi od rozmiarów matrycy żeby program się nam nie wykrzaczył, ale z drugiej strony dobrze by było informować użytkownika po tym jak zadeklarował rozmiary matrycy że jeden z prostokątów się nie zmieści - niech użytkownik zadecyduje co robimy 1) albo zmieniamy rozmiar matrycy 2) albo usuwamy prostokąt z listy.

**Comment by Dawdios** [comment]
Zrobiłem tak: Użytkownik dodaje figury. Jeśli chce je rozmieścić na matrycy to sprawdzane jest czy jakaś figura nie jest za duża - jeśli jest wyskakuje okienko z 3 możliwościami 
a) usuń figurę
b) zmień rozmiar Figury
c) zmień rozmiar matrycy

2 pierwsze podpunkty już działają. Zastanawiam się co ze zmianą rozmiaru matrycy. Jeśli mamy więcej niż jedną matrycę to której zmienić rozmiar ?

**Comment by mmaka** [comment]
OK, ale nie rozumiem czemu bierzesz pod uwagę wiele matryc?

**Comment by mmaka** [comment]
Jest ok, ale można by to jeszcze ulepszyć ;) Chodzi mi o mały drobiazg. Pomysł jest taki: niech informacja o tym że dany prostokąt przekracza rozmiary matrycy będzie dana zanim zostanie naciśnięty przycisk rozmieść. Np. w postaci jakiegoś wykrzyknika w czerwonym kolorze przy id prostokąta - a po najechaniu kursorem niech się pojawia jakiś komunikat. Tak żeby użytkownik mógł się dowiedzieć o błędzie zanim naciśnie przycisk "Rozmieść". Póki co w aktualnej wersji mamy określany rozmiar matrycy na początku, więc od razu po wprowadzeniu rozmiaru można być sprawdzać czy wymiary są ok. 

Poza tym, czy w ogóle ma sens pozwalanie użytkownikowi na naciśnięcie przycisku Rozmieść skoro wiemy, że rozmiary są niewłaściwe. Może raczej okno z tymi trzema możliwościami niech się pojawia od razu po wprowadzeniu za dużego rozmiaru prostokąta?

Weź też pod uwagę, że podczas wprowadzania prostokątów rozmiar matrycy może nie być znany (inaczej niż jest to w aktualnej wersji) i wtedy kontrola rozmiaru prostokątów musi nastąpić po wprowadzeniu rozmiaru matrycy. Do czasu sprawdzenia zgodności rozmiarów przycisk do rozmieszczania powinien być zablokowany.

**Comment by Dawdios** [comment]
Zrobiłem tak jak zasugerowałeś z tym że ikonka wykrzyknika wyświetla się w górnym rogu a nie przy danym prostokącie.
