### ISSUE TITLE
Indeksy dodanych i wczytanych prostokątów - błąd

### ISSUE THREAD

**Issue by mmaka** [mmaka/ProgZesp#21]
@inskript @dawidgrusz1995 
Mamy problem z indeksami: wczytywanie prostokątów z pliku jest możliwe również wtedy gdy już jakieś prostokąty są dodane do listy (ma to sens). Np. mamy zapisane w pliku trzy prostokąty, a aktualnie już dwa mamy na liście. Po wczytaniu tych z pliku otrzymamy w rezultacie następujące id: 1,2,1,2,3. 

Pierwsza sprawa - takie id raczej niczego nie identyfikują, druga sprawa jeśli z wczytanych prostokątów ten pierwszy ma rozmiar większy od rozmiaru matrycy to otrzymamy komunikat, że prostokąt nr 1 ma za duży rozmiar i jeśli z możliwych opcji zdecydujemy się go usunąć, to usuniemy pierwsze wystąpienie prostokąta o id 1 - czyli nie ten, który był za duży, trzecia sprawa - jeśli dodamy trzy prostokąty (do pustej listy), to ich id będą następujące 1,2,3 a gdy zmienię zdanie i usunę 2, to będę miał 1,3 i jak znowu dodam jakiś prostokąt, to będę miał 1,3,4. Po otrzymaniu takiego wyniku pierwsze o czym się myśli, to "gdzie się podziała 2?" ;) Poza tym warto to poprawić, bo łatwiej będzie wczytywać prostokąty z pliku i nadawać im indeksy. Mając trzy już dodane prostokąty do listy wystarczy, że sprawdzę długość listy już wiem, że pierwszy wolny indeks to 4. Natomiast bez tej poprawki mogę mieć dwa prostokąty na liście i dowolne id użyte, więc musiałbym wczytując kolejne prostokąty biegać po liście i sprawdzać czy dany id czasem już gdzieś nie został użyty.

**Comment by Dawdios** [comment]
Wydaje mi się że problem został naprawiony. Po pierwsze po usunięciu jakiejkolwiek figury aktualizowane są ID figur. Teraz nie występuje sytuacja w której jest "dziura" między kolejnymi ID. W sytuacji gdy mamy już dodane prostokąty i chcemy wczytać następne z pliku numery ID są poprawnie numerowane
