### ISSUE TITLE
"Preparing solution..."

### ISSUE THREAD

**Issue by mmaka** [mmaka/ProgZesp#24]
Ponieważ od rozpoczęcia rozmieszczania figur do otrzymania rezultatu czasem mija parę chwil, użytkownika trzeba uświadomić, że coś się dzieje i program się nie zawiesił.

**Comment by inskript** [comment]
Ok, rzeczywiscie mialem cos takiego zrobić.
Tak jak rozmawialiśmy zrobię pasek postępu ktory zalezy od tych iteracji w forze.

**Comment by inskript** [comment]
zrobione
