### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by Dawdios** [mmaka/ProgZesp#26]
Dodałem możliwość zapisu projektu do PDF. Użytkownik ma możliwość wyboru informacji znajdujących się w tworzonym pliku. Jak na razie są tylko dwie możliwości: obrazy matryc + wszystkie informacje z okna informacyjnego. Jakie warianty powinny być dostępne do wyboru ?

**Comment by mmaka** [comment]
Myślę, że mogą być użyteczne jakieś opcje dotyczące sposobu rozmieszczania obrazów matryc na stronie...:)

Wiesz, czasem chciałbym mieć jeden rysunek na stronie żeby np. trzy użyte matryce przygotowywały trzy osoby jednocześnie, a czasem mogę chcieć mieć wszystkie na jednej stronie. 
Można by dać użytkownikowi możliwość wybrania czy chce cztery matryce na stronę czy dwie (chodzi mi o takie opcje jak przy drukowaniu).

Wydaje mi się, że najlepiej byłoby zrobić parę rozmieszczeń prostokątów i zobaczyć jak te pdfy wyglądają.

**Comment by inskript** [comment]
Naprawdę nie wiem czy kolejne komplikowanie jest nam potrzebne, wg mnie jest dobrze tak jak jest, a wymyślać nowych featerów można bez liku, ale czy to ma sens...

**Comment by mmaka** [comment]
Problem pojawił się gdy rozmieszczanych było dużo prostokątów na wielu matrycach. Wtedy otrzymywaliśmy pdf-a z np. 30 linijkami info o prostokątach i trzema stronami z matrycami. Jak chciało się dane prostokąta z rysunku, to trzeba było wyszukiwać go po id w spisie prostokątów. Więc dorzuciliśmy opcję drukowania matryc z informacją o tych prostokątach, które znajdują się na danej matrycy.

**Comment by Dawdios** [comment]
Zastanawiam się czy podczas zapisywania Matryc w razie potrzeby obracać je tak aby lepiej dopasować je do wolnej przestrzeni

**Comment by mmaka** [comment]
Może po prostu wrzuć przycisk, który pozwoli użytkownikowi wybrać. Tylko chyba jakiś podgląd by się wtedy przydał żeby można było zaobserwować różnicę. Tak na sucho (tzn. bez patrzenia jakie jest ustawienie na stronie), jako użytkowniki chyba nie miałbym zdania co wolę.
