### ISSUE TITLE
Nowy wygląd aplikacji

### ISSUE THREAD

**Issue by inskript** [mmaka/ProgZesp#27]
Pracuje nad nowym wyglądem, 
Dawid mówi że ok,
chciałem jeszcze Michał spytać o twoje zdanie, czy dobry kierunek?

![image](https://cloud.githubusercontent.com/assets/23060438/21849366/a5baa91c-d805-11e6-8e67-c48a55c30185.png)

**Comment by mmaka** [comment]
Mnie się podoba! Właśnie taki efekt rozmycia miałem na myśli.

**Comment by inskript** [comment]
No tak właśnie taki wygląd miałem na myśli jak Wam mówiłem.
Nowy wygląd jest praktycznie gotowy )prócz scroll bar ale to w toku)... 
Zamykam.
