### ISSUE TITLE
Drobiazgi do zrobienia

### ISSUE THREAD

**Issue by mmaka** [mmaka/ProgZesp#33]
@inskript 
@dawidgrusz1995

**Comment by mmaka** [comment]
- Wydaje mi się, że określanie rozmiaru matrycy mogłoby być możliwe z poziomu okna głównego (a nie przez plik->określ....). 
- W miejscu gdzie ustawiamy czas nie wiadomo jakich jednostek użyć.  Propozycje: "Czas (w sekundach)", "Czas (sek)", "Czas (s)". Może być też coś innego - grunt żeby było wiadomo w jakich jednostkach (w pomocy jest informacja, że to mają być sekundy)

**Comment by inskript** [comment]
zrobione
